name: demo
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #fronted - view 
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^25.1.40
  syncfusion_flutter_gauges: ^25.1.41
  syncfusion_flutter_core: ^25.1.40
  multi_dropdown: ^2.1.4
  lottie: ^3.1.0
  #set managment
  provider: ^6.0.5
  #cache
  shared_preferences: ^2.2.0
  #language
  easy_localization: ^3.0.0
  #router
  auto_route: ^7.6.0
  #network
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  #model parse 
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  #core eştlik kontrol
  equatable: ^2.0.5
  #network control
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.12
  package_info_plus: ^5.0.1
  #image
  image_picker: ^1.0.1
  cached_network_image: ^3.3.1
  #file
  file_picker: ^6.2.0
  #permission
  permission_handler: ^11.3.0
  app_settings: ^5.0.0
  #qr 
  qr_code_scanner: ^1.0.1
  pretty_qr_code: ^3.3.0
  #map 
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlng: ^2.0.7
  latlong2: ^0.9.1
  #locaition
  location: ^6.0.1 
  #onesignal
  onesignal_flutter: ^5.1.2
  #share 
  # share_plus: ^9.0.0
  clipboard: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator:                    
  build_runner: 
  freezed: ^2.4.1
  very_good_analysis: ^4.0.0+1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/jsons/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #